version: '3.3'

services:
  postgresql:
    image: postgres:9.6
    ports:
      - 6432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test

  flyway:
    image: boxfuse/flyway
    entrypoint: bash -c "sleep 3 && flyway -configFile=./conf/flyway.conf clean migrate"
    volumes:
      - ./flyway/conf:/flyway/conf
      - ./flyway/sql:/flyway/sql
    depends_on:
      - postgresql
    links:
      - postgresql

  integration_test:
    image: golang
    volumes:
      - ../:/go/src/github.com/netology/dao-pattern
    working_dir: /go/src/github.com/netology/dao-pattern
    command: sh -c "sleep 5;GO111MODULE=on go mod vendor && go test ./... -tags=integration -count=1 -race"
    depends_on:
      - postgresql
      - flyway
    links:
      - postgresql
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_SCHEMA=test
      - DB_PORT=5432
      - DB_HOST=postgresql